### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by MaxAlberti**
Added Issue templates

### CODE REVIEW

**Review by Erix0815 — APPROVED** [review]
tldr, lgtm

**Comment by leandergmeiner** [comment]
Is this necessary, especially this far into the project?

**Comment by MaxAlberti** [comment]
> Is this necessary, especially this far into the project?

Yes, it gives us a higher GitHub community score xD

**Comment by leandergmeiner** [comment]
Not really convincing, let's just leave it out of this. Especially since the template is much more effort, than what e.g. I do and I think that is sufficient (that is just a description and the criteria for acceptance).

**Pull request merged**
