### PR TITLE
Setup project structure

### PR DESCRIPTION
**Pull request by MaxAlberti**
### Any project requires a structure to enable effective development and cooperation.
# Goals
The structure should be:
- In compliance with the Golang standards
- Able to encompass frontend and backend
- Easy to implement
- Extendable

# Tasks
1. Implement the structure over the prototype
2. Create templates for structure components
3. Write a Wiki section describing the structure

### CODE REVIEW

**Comment by MaxAlberti** [comment]
NOT ready for review!
WTF @V1nzent ???

**Comment by MaxAlberti** [comment]
https://www.atatus.com/blog/what-is-git-branch-and-how-to-use-it/
@V1nzent

**Comment by MaxAlberti** [comment]
# Project Structure
YAAC's project structure is further discussed in [this](https://github.com/DHBW-SE-2023/Wiki/blob/main/Pages/Structure.md) wiki page.
## Online Resources
I chose to implement the most popular Golang project layout structure I could find.
- https://github.com/golang-standards/project-layout
This layout is compliant with the Golang standards, can handle multiple, segregated internal packages and is extendable. It is, however, quite different from the more popular layouts that C-like languages use.
- MVVM: https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93viewmodel
- Along with this guide to get rid of import circles while maintaining two way calls: https://jogendra.dev/import-cycles-in-golang-and-how-to-deal-with-them

**Review by JonasZagst — APPROVED** [review]
looks good and was proven in prototype

**Pull request merged**
