### PR TITLE
Demon: Mark all retrieved mails as read

### PR DESCRIPTION
**Pull request by leandergmeiner**

### CODE REVIEW

**Review by MaxAlberti — APPROVED** [review]

**Review by JonasZagst — COMMENTED** [review]
should we really do this?

**Comment by leandergmeiner** [comment]
> should we really do this?

What would speak against it?

**Comment by JonasZagst** [comment]
> > should we really do this?
> 
> What would speak against it?

That we decide for the user if one of his mails is read or not. This decision should be the users to make. This is the point where the service goes from reading to actually changing data.

**Comment by leandergmeiner** [comment]
I think it is fine, because we are only marking E-Mails as read that are designated for the program (by including "Anwesenheitsliste" in the subject).

**Pull request merged**
