### PR TITLE
Create LICENCE

### PR DESCRIPTION
**Pull request by EvaMatz**
Created Licence. Used licence: MIT
Can be changed later in needed, need a licence in project to test README in Wiki

### CODE REVIEW

**Review by MaxAlberti — CHANGES_REQUESTED** [review]
We can't use an MIT license due to our dependencies. We should investigate if an AGPLv2 is strict enough.

**Comment by MaxAlberti** [comment]
See https://github.com/google/go-licenses

**Comment by MaxAlberti** [comment]
According to `go-licenses` our current licenses are: 
[licenses.csv](https://github.com/DHBW-SE-2023/YAAC/files/13486948/licenses.csv)
Run 
```shell
go-licenses report ./cmd/yaac > licenses.csv 2> errors
``` 
to recreate

**Comment by MaxAlberti** [comment]
According to [GNU](https://www.gnu.org/licenses/license-list.html) the GPLv3 License is compatible with all our licenses.

**Review by MaxAlberti — APPROVED** [review]
Thi license should be fine

**Review by leandergmeiner — APPROVED** [review]

**Pull request merged**
