### PR TITLE
Implemented improg on list upload as well as some fixes

### PR DESCRIPTION
**Pull request by MaxAlberti**
My fixes and features for improg frontend issues

### CODE REVIEW

**Review by leandergmeiner — COMMENTED** [review]
Why are all German errors starting with a lower case letter?

**Comment by MaxAlberti** [comment]
> Why are all German errors starting with a lower case letter?

because its against go convention to start errors with uppercase letters. gopls and staticcheck will generate a warning. (That warning wont work if the string is not directly inside the error function)

**Review by leandergmeiner — COMMENTED** [review]
Why are the errors in German anyways, I'm guessing that they are shown to the user?

**Comment by MaxAlberti** [comment]
> Why are the errors in German anyways, I'm guessing that they are shown to the user?

Yes

**Review by leandergmeiner — APPROVED** [review]
Doesn't crash

**Pull request merged**
